### ISSUE TITLE
Add a button to upload json file for data backup

### ISSUE THREAD

**Issue by g-savitha** [rahuldkjain/github-profile-readme-generator#103]
Adding a button to upload the downloaded .json file would make things easier instead of copy-pasting the data from .json file
![image](https://user-images.githubusercontent.com/31612459/92601227-2f5a8b00-f2ca-11ea-8ce2-72f0aec38420.png)

**Comment by rahuldkjain** [comment]
Definitely. Users might get confused with current config options. This feature will make it more understandable.

**Comment by Tailine** [comment]
Hi @rahuldkjain , I would like to work on it
