### ISSUE TITLE
Add username validation for hackerearth and geeksforgeeks links

### ISSUE THREAD

**Issue by g-savitha** [rahuldkjain/github-profile-readme-generator#104]
Throw a warning, when user enters username in the wrong format.

- For hackerearth, username must begin with: '@' 
  - format : `@username`
- For GFG, username must be appended with : '/profile'
  - format: `username/profile`

**Comment by g-savitha** [comment]
assign this to me @rahuldkjain

**Comment by rahuldkjain** [comment]
Yep, this will be a good validation. Should I assign this to you?

**Comment by g-savitha** [comment]
Yes please

**Comment by g-savitha** [comment]
Sure :)

**Comment by CodeSarthak** [comment]
Hey @g-savitha , good idea to add this validation. Let me know if you are still working on this or if you require any help :D

**Comment by g-savitha** [comment]
Thanks @CodeSarthak :). I haven't started working on this yet. Planning to do this as a part of hacktoberfest :)
