### ISSUE TITLE
Addition of scikit-learn under AI/ML section.

### ISSUE THREAD

**Issue by Akshat1305** [rahuldkjain/github-profile-readme-generator#106]
scikit-learn would be a good addition for Machine Learning.

(https://scikit-learn.org/stable/)

**Comment by rahuldkjain** [comment]
@Akshat1305 would you like to contribute?

**Comment by Akshat1305** [comment]
@rahuldkjain Thanks for acknowledging. I wish I could, but I am not good at it. That's the reason I added the enhancement label as a suggestion.

**Comment by MaheshBharadwaj** [comment]
Can i try out this issue, planning to use this [link](https://commons.wikimedia.org/wiki/File:Scikit_learn_logo_small.svg)
