### ISSUE TITLE
Add Flutter or Dart in Skills.

### ISSUE THREAD

**Issue by shivaniaakanksha** [rahuldkjain/github-profile-readme-generator#11]
Flutter or Dart is not mentioned in Skills Category. A huge number of developers are working on his too. I think it can be considered too.

**Comment by rahuldkjain** [comment]
@shivaniaakanksha would you like to work on this isse?

**Comment by shivaniaakanksha** [comment]
Sure, I will try to do this. Shall I raise the PR if it gets solved?  @rahuldkjain

**Comment by rahuldkjain** [comment]
@shivaniaakanksha yep🌟. I've assigned the issue to you

**Comment by rahuldkjain** [comment]
@shivaniaakanksha Flutter & Dart icons are not available on [devicon](https://konpa.github.io/devicon/) which are being used here. So you are free to use icons from other sources.

**Use SVG Icons only**

You can use these icons if you want:
- flutter: https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/flutter.svg
- dart: https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/dart.svg
