### ISSUE TITLE
Add Twitter Badge with followers count in README

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#119]
Add a new add-on to display twitter badge with followers-count.

The badge should take the user to the corresponding twitter profile onClick.

[![rahuldkjain](https://img.shields.io/twitter/follow/rahuldkjain?logo=twitter&style=for-the-badge)](https://twitter.com/Rahuldkjain)

**Comment by Maddoxx88** [comment]
Hello, I would like to contribute to this issue.

**Comment by Maddoxx88** [comment]
Ohk @rahuldkjain

**Comment by Maddoxx88** [comment]
Added complete support for Twitter Badge in [#157](https://github.com/rahuldkjain/github-profile-readme-generator/pull/157) and [#162 ](https://github.com/rahuldkjain/github-profile-readme-generator/pull/162)

**Comment by rahuldkjain** [comment]
fixed by #157 and #162

**Comment by samir-el-asri** [comment]
It's saying "unparseable json response" !!
