### ISSUE TITLE
Trim the variables

### ISSUE THREAD

**Issue by rajat2502** [rahuldkjain/github-profile-readme-generator#12]
**Describe the bug**
Trim the variables which are styled bold in the readme. If any spaces before/after are left then GitHub readme will show that space and will not make it bold

**Expected behavior**
Trimmed variables

**Screenshots**
![image](https://user-images.githubusercontent.com/42200276/87871846-9a29cd00-c9d1-11ea-9e8b-67231c59c285.png)
preview: 
![image](https://user-images.githubusercontent.com/42200276/87871864-c2b1c700-c9d1-11ea-9b43-4b92d05a051a.png)

Would you like to work on this issue? - Yes

**Comment by rahuldkjain** [comment]
Thanks for opening the issue @rajat2502 🙇. I have assigned the issue to you.

**Comment by rajat2502** [comment]
Thanks @rahuldkjain I will make a PR for the same.
