### ISSUE TITLE
add resume field under work category

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#125]
**Describe the solution you'd like**
Add resume input field between blog and fun fact.
<img width="987" alt="Screenshot 2020-09-25 at 11 30 56 AM" src="https://user-images.githubusercontent.com/26406279/94232002-b7739e00-ff22-11ea-8794-329feef896b3.png">

There will be two fields in the row.
1. Prefix: `📄 Resume`
2. Link: `resume link`

**Comment by Jigyasa-Kumari** [comment]
Hey, can I work on this?

**Comment by rahuldkjain** [comment]
@Jigyasa-Kumari sure. 
Please join the discord server for further discussions.
Server Link: https://discord.gg/HHMs7Eg

**Comment by rahuldkjain** [comment]
@Jigyasa-Kumari I have assigned the issue, you can start working now by forking the repository.

**Comment by nidhi-bhanushali** [comment]
Is it that only one person can work on one issue?

**Comment by rahuldkjain** [comment]
Yup @nidhi-bhanushali. There is no point if more than one people solve the same issue.
Since @Jigyasa-Kumari is not responding, then I think I should assign this issue to you too.

**Comment by nidhi-bhanushali** [comment]
Great , Thankyou.

**Comment by rahuldkjain** [comment]
@nidhi-bhanushali
Join Discord Server for discussing issues, pull-requests, new features, etc.

Discord Server Link- https://discord.gg/HHMs7Eg

**Comment by sambhavjain9138** [comment]
Hello @rahuldkjain @nidhi-bhanushali 
Incase no one is working on the issue, can i contribute on the same? 

Regards,
Sambhav

**Comment by nidhi-bhanushali** [comment]
I'm!

**Comment by sambhavjain9138** [comment]
Thank for the update @nidhi-bhanushali

**Comment by nidhi-bhanushali** [comment]
I've made a PR for this issue , kindly check.

**Comment by rahuldkjain** [comment]
@nidhi-bhanushali Please mention the issue in the PR description.

**Comment by nidhi-bhanushali** [comment]
Okay , I'll edit it

**Comment by nidhi-bhanushali** [comment]
Thanks for guiding me throughout!
