### ISSUE TITLE
align skills to the left

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#127]
**Is your feature request related to a problem? Please describe.**
The center alignment of skill icons seems a bit messy.
<img width="904" alt="Screenshot 2020-09-24 at 12 53 41 PM" src="https://user-images.githubusercontent.com/26406279/94236742-5ac8b100-ff2b-11ea-9c96-8b198c8c4b3d.png">

**Describe the solution you'd like**
Aligning the skill icons to the left under the `Skills & Tools` label will it cooler.
<img width="902" alt="Screenshot 2020-09-24 at 12 46 52 PM" src="https://user-images.githubusercontent.com/26406279/94236865-8350ab00-ff2b-11ea-803c-bf5bed518ea3.png">

Join the Discord Server for further discussions.
Server Link: https://discord.gg/HHMs7Eg

**Comment by sarbikbetal** [comment]
I would like to take this as well :grinning: .

**Comment by sarbikbetal** [comment]
PR: #130 addresses this issue :v:
