### ISSUE TITLE
Skills icons to redirect visitor to related website.

### ISSUE THREAD

**Issue by priyanshnama** [rahuldkjain/github-profile-readme-generator#128]
### After seeing a particular skill in some profile . the visitor would like to know more about that but unfortunately on clicking the icon the same logo appears in new tab.

**Solution i would like**
link related websites to their logos.
For ex - clicking on python icon should open https://www.python.org/

**Comment by rahuldkjain** [comment]
@priyanshnama Sounds great. We can easily do this by wrapping the `img` tags by `a` tags.

Would you like to work on this?

**Comment by priyanshnama** [comment]
@rahuldkjain 
Ya i would love to..
can you link the concerned file as i don't have much idea of whole code base as of now.

**Comment by priyanshnama** [comment]
@rahuldkjain 
i think we should create a file with key-value pairs.
key will be the skill and value will be it's related website.
then import them to markdown to js and pass $skill to get the link and then push it. the code snippet should look somewhat similar to
```js
skills.forEach(skill => {
            if (props.skills[skill]) {
                listChosenSkills.push(`<a href = "${url[skill]}"> <img src="${icons[skill]}" alt="${skill}" width="40" height="40"/> </a>`);
            }
        });
```

**Comment by rahuldkjain** [comment]
> @rahuldkjain
> i think we should create a file with key-value pairs.
> key will be the skill and value will be it's related website.
> then import them to markdown to js and pass $skill to get the link and then push it. the code snippet should look somewhat similar to
> 
> ```js
> skills.forEach(skill => {
>             if (props.skills[skill]) {
>                 listChosenSkills.push(`<a href = "${url[skill]}"> <img src="${icons[skill]}" alt="${skill}" width="40" height="40"/> </a>`);
>             }
>         });
> ```

Yep, this will solve the problem.
The same must be done in `markdownPreview.js`

**Comment by jaideepghosh** [comment]
Hey @rahuldkjain 
I want to contribute to solve this issue. Please assign it to me.
