### ISSUE TITLE
add yourself as a contributor in the README

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#131]
Only for those who have contributed to this project. PRs of real contributors will be accepted only.

Comment on the Issue asking @all-contributors to add a contributor:
**`@all-contributors please add <username> for <contributions>`**

`<contribution>`: See the [Emoji Key (Contribution Types Reference)](https://allcontributors.org/docs/en/emoji-key) for a list of valid contribution types.

The bot will then create a Pull Request to add the contributor, then reply with the pull request details.
![](https://allcontributors.org/docs/assets/bot-usage.png)

PS: Please mention your commits to qualify as a contributor.

**Comment by rahuldkjain** [comment]
@all-contributors please add @g-savitha for Code

**Comment by sarbikbetal** [comment]
@all-contributors please add @sarbikbetal for code

**Comment by Hardik0307** [comment]
@all-contributors please add @Hardik0307 for code

**Comment by insaurabh** [comment]
@all-contributors please add @insaurabh for Code

**Comment by ujjwal404** [comment]
@all-contributors please add @ujjwal404 for code

**Comment by g-savitha** [comment]
@all-contributors please add @g-savitha for Code

**Comment by antonkomarev** [comment]
@all-contributors please add @antonkomarev for plugin

**Comment by anshdhinhgra47** [comment]
@all-contributors please add @anshdhinhgra47 for code

**Comment by alinasahoo** [comment]
@all-contributors please add @alinasahoo for code

**Comment by utsav00** [comment]
@all-contributors please add @utsav00 for code

**Comment by Maddoxx88** [comment]
@all-contributors please add @Maddoxx88  for Code

**Comment by abhijit-hota** [comment]
@all-contributors please add @abhijit-hota for code

**Comment by YashKandalkar** [comment]
@all-contributors please add @YashKandalkar for code

**Comment by jaideepghosh** [comment]
@all-contributors please add @jaideepghosh for code

**Comment by KKVANONYMOUS** [comment]
@all-contributors please add @KKVANONYMOUS  for code

**Comment by avnish1306** [comment]
@all-contributors please add @avnish1306 for code

**Comment by abhijit-hota** [comment]
@all-contributors please add @abhijit-hota for test

**Comment by Mohitmadhav** [comment]
@all-contributors please add @Mohitmadhav for Code

**Comment by amruta-kashikar** [comment]
@all-contributors please add @amruta-kashikar for code

**Comment by MaheshBharadwaj** [comment]
@all-contributors please add @MaheshBharadwaj for code

**Comment by MaheshBharadwaj** [comment]
> @MaheshBharadwaj
> 
> This project's configuration file has malformed JSON: .all-contributorsrc. Error:: Unexpected token { in JSON at position 1344

@rahuldkjain is add-contributor broken or was the request incorrect?

**Comment by harshcut** [comment]
@all-contributors please add @harshcut for code

**Comment by Aditya-ds-1806** [comment]
@all-contributors please add @Aditya-ds-1806 for code
