### ISSUE TITLE
Lengthy text in addons section goes below the checkbox on smaller screens

### ISSUE THREAD

**Issue by YashKandalkar** [rahuldkjain/github-profile-readme-generator#143]
**Is your feature request related to a problem? Please describe.**
 Lengthy text in addons section wraps around and goes below the checkbox on smaller screens.
![image](https://user-images.githubusercontent.com/35102959/94345971-192d2880-0047-11eb-9701-7dfe722b7b13.png)

**Describe the solution you'd like**
Center the checkbox vertically, add some left padding to the text
![image](https://user-images.githubusercontent.com/35102959/94346017-71fcc100-0047-11eb-8eff-60d1f5a85b24.png)

**Comment by YashKandalkar** [comment]
@rahuldkjain Also, what do you think of making smaller components to reuse? `In addons.js`, there are 6 same divs (with some props changes) for different addons. A smaller component can be made which can take props like `text`, `inputId`, etc. This isn't much, just makes the code a little cleaner and readable.

![image](https://user-images.githubusercontent.com/35102959/94346813-ca828d00-004c-11eb-8f66-150c271cc449.png)

I could fit these 4 in screenshot :)

**Comment by rahuldkjain** [comment]
It will be good to follow the DRY principle here. Go on 👍.
I am really thankful for your great suggestions and help.

**Comment by YashKandalkar** [comment]
Alrighty, I'll do both these changes and make a PR.
No problem :smiley:
