### ISSUE TITLE
eslint warnings

### ISSUE THREAD

**Issue by YashKandalkar** [rahuldkjain/github-profile-readme-generator#146]
**Is your feature request related to a problem? Please describe.**
There are following eslint warnings in the code which are shown during the dev build:
![image](https://user-images.githubusercontent.com/35102959/94697800-3e2adf80-0356-11eb-8f33-0d5a631a296f.png)

**Describe the solution you'd like**
Most of these warnings can be resolved by reading the message they provide.

I can make a PR to resolve these warnings 🍀

**Comment by abhijit-hota** [comment]
I was going to address this. Great to see it resolved! 😄
