### ISSUE TITLE
add Adobe Xd skill in software category

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#149]
add Adobe Xd in software category.
<img width="1196" alt="Screenshot 2020-10-01 at 10 24 09 AM" src="https://user-images.githubusercontent.com/26406279/94769694-46276580-03d0-11eb-9a15-50fb99827bcf.png">

SVG Logo: https://cdn.worldvectorlogo.com/logos/adobe-xd.svg

**Comment by abhaybhatt** [comment]
@rahuldkjain can i work on it?

**Comment by rahuldkjain** [comment]
Sure @rahuldkjain.

Join Discord Server for discussing issues, pull-requests, new features, etc.
Discord Server Link- https://discord.gg/HHMs7Eg

**Comment by xybervenom** [comment]
hey,  I am new to contributing into open source can I directly solve the issue using a pull request or do I have to take some permit/access to solve an open issue?

**Comment by vijaygupta18** [comment]
> hey, I am new to contributing into open source can I directly solve the issue using a pull request or do I have to take some permit/access to solve an open issue?

you can commit here any projects https://github.com/vijaygupta18/Hacktober-2020

**Comment by abhaybhatt** [comment]
@rahuldkjain please review it ?
