### ISSUE TITLE
fix discord server link in README

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#153]
**Describe the bug**
The Discord Server link in README is invalid.

**Screenshots**
<img width="708" alt="Screenshot 2020-10-01 at 12 59 23 PM" src="https://user-images.githubusercontent.com/26406279/94780513-2f8c0900-03e6-11eb-982c-ada35c828566.png">

**Valid Discord Server Link**
Server Link: https://discord.gg/HHMs7Eg

**Comment by kala2** [comment]
Hello, could you assign to me please?

**Comment by abhaybhatt** [comment]
@rahuldkjain i would love to fix this to get started in open source?

**Comment by rahuldkjain** [comment]
Join discord server for further discussions related to Hacktoberfest, features, issues, and pull-requests
Server Link: https://discord.gg/HHMs7Eg

**Comment by rahuldkjain** [comment]
@abhaybhatt I assigned it to @kala2. I'll be opening more issues today, you can pick from them.

**Comment by rahuldkjain** [comment]
fix #156
