### ISSUE TITLE
Make titles left alligned

### ISSUE THREAD

**Issue by shajanjp** [rahuldkjain/github-profile-readme-generator#158]
Make title texts left-aligned. Left-aligned titles are neat and get more attractive from users.

Current:
![Screenshot from 2020-10-01 15-04-51](https://user-images.githubusercontent.com/2943609/94793301-e5138800-03f7-11eb-8391-d9bc7f7e94d7.png)

Expected:
![Screenshot from 2020-10-01 15-05-26](https://user-images.githubusercontent.com/2943609/94793307-e8a70f00-03f7-11eb-910e-a18c09ee9be8.png)

**Comment by Haqverdi** [comment]
i can fix this

**Comment by Harshi7016** [comment]
I can take up this issue,
Is it still open?

**Comment by AyushRajSharma** [comment]
i can work with this issue,
please assign me
