### ISSUE TITLE
modify existing footer with new one

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#163]
**Is your feature request related to a problem? Please describe.**
The existing footer looks just OK.

**Describe the solution you'd like**
I want to modify the existing footer with a fresh design.
![Footer](https://user-images.githubusercontent.com/26406279/94810399-9541ba80-0411-11eb-98cd-783e9865aa58.png)

**Task**
Develop the above footer structure. No need to add links. I'll open more issues to add links.

Join the **Discord Server** for further discussions.
Server Link: https://discord.gg/HHMs7Eg

**Comment by priyanshnama** [comment]
@rahuldkjain i would like to take this one

**Comment by thauska** [comment]
I can take this

**Comment by rahuldkjain** [comment]
@priyanshnama You can pick up other issues.

**Comment by GabrielModog** [comment]
Can I pick this one?

**Comment by rahuldkjain** [comment]
any update @thauska?

**Comment by thauska** [comment]
#246
