### ISSUE TITLE
remove youtube stats from README

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#169]
**Is your feature request related to a problem? Please describe.**
Remove `YouTube Stats` from README

<img width="708" alt="Screenshot 2020-10-01 at 7 47 39 PM" src="https://user-images.githubusercontent.com/26406279/94821354-1eabb980-041f-11eb-89a0-720728b95841.png">

Join the **Discord Server** for further discussions.
Server Link: https://discord.gg/HHMs7Eg

**Comment by quintenbuis** [comment]
I'll pick this one up.
