### ISSUE TITLE
Add Unity to Other

### ISSUE THREAD

**Issue by KKVANONYMOUS** [rahuldkjain/github-profile-readme-generator#184]
@rahuldkjain 
I would love to add **Unity-Game Engine** in **Other** as it is quite famous and used by many game developers

Join the **Discord Server** for further discussions.

Server Link: https://discord.gg/HHMs7Eg

**Comment by rahuldkjain** [comment]
@KKVANONYMOUS Cool. I guess we can create a separate category for game engines.

**Comment by KKVANONYMOUS** [comment]
@rahuldkjain Sure!! It's a good idea. I'll work on it

**Comment by yubarajsingh** [comment]
I want to add unreal engine to the game Engines

**Comment by rahuldkjain** [comment]
Sure @yubarajsingh. Open an issue for the same.
