### ISSUE TITLE
Add DevOps skills

### ISSUE THREAD

**Issue by MuhBayu** [rahuldkjain/github-profile-readme-generator#185]
**Is your feature request related to a problem? Please describe.**
Add DevOps skills like CI/CD tools and monitoring tools.

Join the **Discord Server** for further discussions.

Server Link: https://discord.gg/HHMs7Eg

**Comment by g-savitha** [comment]
cool. Shall I assign this to you? As you have already raised a PR

**Comment by MuhBayu** [comment]
> cool. Shall I assign this to you? As you have already raised a PR

sure, you can assign it to me and also i have already create a PR
