### ISSUE TITLE
no option to get back to markdown again.

### ISSUE THREAD

**Issue by arjuna1729** [rahuldkjain/github-profile-readme-generator#19]
**Is your feature request related to a problem? Please describe.**
After the markdown is generated upon clicking the **preview** option, there was **no** option to get to the markdown again.

**Describe the solution you'd like**
After clicking the preview option, there should be an option to get back to markdown again.

**Comment by rahuldkjain** [comment]
@arjuna1729 click the same button again, you will see the markdow

**Comment by arjuna1729** [comment]
> @arjuna1729 click the same button again, you will see the markdown

Then it will be great if the icon changes from eye to code

**Comment by rahuldkjain** [comment]
@arjuna1729 that would be great

**Comment by rahuldkjain** [comment]
fixed: pull #22
