### ISSUE TITLE
Add  11ty, Scully, Sculpin, Sapper under static site generators

### ISSUE THREAD

**Issue by g-savitha** [rahuldkjain/github-profile-readme-generator#191]
Add  11ty, Scully, Sculpin, Sapper under static site generators

Join the **Discord Server** for further discussions.

Server Link: https://discord.gg/HHMs7Eg

**Comment by vivek32ta** [comment]
Hi @g-savitha 

I'd love to work on this, if you could assign it to me. Thank.

Best,
Vivek

**Comment by g-savitha** [comment]
sure @vivek32ta
