### ISSUE TITLE
Add separators to skill sections to differentiate between each easily

### ISSUE THREAD

**Issue by ram170** [rahuldkjain/github-profile-readme-generator#196]
**Is your feature request related to a problem? Please describe.**
It is pretty tough to spot each skill section since there's no separator.

**Describe the solution you'd like**
Add CSS to skill section title to differentiate between each easily.

**Describe alternatives you've considered**
Simple horizontal line after each skill section but it doesn't look good.

**Additional context**
Kinda like this: 

![css](https://user-images.githubusercontent.com/46366477/94913771-743ba100-04c7-11eb-8949-a0de658f83e1.png)

**Comment by ram170** [comment]
@rahuldkjain @g-savitha There's an alternative to add border just to the title span instead of the whole div.  Kindly assign it to me if this should be done

**Comment by rahuldkjain** [comment]
Not necessary right now.
