### ISSUE TITLE
Add some missing logos

### ISSUE THREAD

**Issue by pro-nav** [rahuldkjain/github-profile-readme-generator#205]
Add the Arduino logo in others section.
[Arduino Logo](https://cdn.worldvectorlogo.com/logos/arduino-1.svg)

Add the MATLAB logo in the programming languages section.
[MATLAB Logo](https://img.icons8.com/nolan/420/matlab.png)

Add the Solidworks logo in the software section.
[Solidworks Logo](https://cdn.worldvectorlogo.com/logos/solidworks.svg)

**Comment by pro-nav** [comment]
MATLAB logo is in .png format so I did not add the following.

**Comment by sixthcodebrewer** [comment]
Can I work on the same, I can design one.

**Comment by Aditya-ds-1806** [comment]
Hey I made a PR that fixes this #237 . Please review
