### ISSUE TITLE
Add Perl to Languages

### ISSUE THREAD

**Issue by Darkangeel-hd** [rahuldkjain/github-profile-readme-generator#207]
Perl is still widely used in the software industry.
Not so much in new developments but it is in old ones.

So it would be nice to have it here.

PR #179

**Comment by vikashgaya916** [comment]
Hi, I would like to work on this issue. Is it open to be worked on?

**Comment by Darkangeel-hd** [comment]
@vikashgaya916 
I already did it (#179 ) when opening the issue,
but as @rahuldkjain decides
^^
