### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by gabrieldiaspereira** [rahuldkjain/github-profile-readme-generator#21]
**Describe the bug**
The error occurs when the preview option is checked, when clicking on 'download' we do not get any answer, however when clicking on markdown it is possible to download.

**To Reproduce**
-After clicking "generate readme"
1. Click on 'preview button'
2. Click on 'download button'

**Desktop:**
 - OS: [ubuntu]
 - Browser [chrome]

**Comment by rahuldkjain** [comment]
thanks @gabrieldiaspereira. I am fixing this

**Comment by rahuldkjain** [comment]
fixed : pull #23
