### ISSUE TITLE
A searchbox for making it easier to search skills.

### ISSUE THREAD

**Issue by j23saw** [rahuldkjain/github-profile-readme-generator#217]
**Is your feature request related to a problem? Please describe.**
There seems to be a lot of options in skills to choose from and manually searching and selecting them makes this a bit of a tedious task.

**Describe the solution you'd like**
I want a searchbox where I can easily filter through the Skills and select them. Makes the workflow a little convenient.

**Describe alternatives you've considered**
None

**Additional context**
Here's a basic implementation by me![ezgif.com-video-to-gif.gif](https://user-images.githubusercontent.com/34836779/94985052-84f42180-0570-11eb-844d-36d9133a49e4.gif)

Join the **Discord Server** for further discussions.

Server Link: https://discord.gg/HHMs7Eg

**Comment by j23saw** [comment]
I would like to work on this.

**Comment by YashKandalkar** [comment]
Great feature! You can also try to remove the tabs which don't have any option left inside after filtering.

**Comment by j23saw** [comment]
Alright! Working on it!

**Comment by j23saw** [comment]
Here's my attempt
![ezgif com-video-to-gif(1)](https://user-images.githubusercontent.com/34836779/95128250-c6eeb480-0776-11eb-83df-d88c5ace7d36.gif)
