### ISSUE TITLE
fix warning in local environment

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#225]
**Describe the bug**
A warning is coming up in the local environment.

**To Reproduce**
Run the code locally.

**Expected behavior**
No warning

**Screenshots**
<img width="1014" alt="Screenshot 2020-10-04 at 9 39 55 AM" src="https://user-images.githubusercontent.com/26406279/95006819-08bc1580-0626-11eb-8afe-8fa252b3fc70.png">

Join the **Discord Server** for further discussions.
Server Link: https://discord.gg/HHMs7Eg

**Comment by dibakar95** [comment]
@rahuldkjain  Can i take this issue ?

**Comment by rahuldkjain** [comment]
Sure @dibakar95.

**Comment by Aditya-ds-1806** [comment]
Hey, I made a PR that fixes this #237 . Please review.

**Comment by msriaz** [comment]
I have added this PR please review #245
