### ISSUE TITLE
change version of gatsby-plugin-sharp in package.json

### ISSUE THREAD

**Issue by YashKandalkar** [rahuldkjain/github-profile-readme-generator#228]
**Is your feature request related to a problem? Please describe.**
The latest version of `gatsby-plugin-sharp` (2.6.38) has some bugs, as reported by some people.

**Describe the solution you'd like**
Change the version of `gatsby-plugin-sharp` in `package.json` 
from 
> "gatsby-plugin-sharp": "^2.6.14"

to 
> "gatsby-plugin-sharp": "2.6.14"

So npm doesn't update the version.

**Comment by DreamsOfImran** [comment]
Hey, can I work on this?

**Comment by Mohitmadhav** [comment]
Can I get that ?

**Comment by rahuldkjain** [comment]
@DreamsOfImran You can pick up other issues.

Join the discord server for quick updates related to issues, PRs, and hacktoberfest.
Server Link: https://discord.gg/HHMs7Eg

**Comment by YashKandalkar** [comment]
Closing, fixed in #241
