### ISSUE TITLE
StackOverflow URL is Broken

### ISSUE THREAD

**Issue by MuhaddiMu** [rahuldkjain/github-profile-readme-generator#24]
**Describe the bug**
Every time, I add the Stackoverflow username, it leads to broken URLs. 
Username: Muhaddis
Dynamic Link: https://stackoverflow.com/Muhaddis which is actually 404

**Expected behavior**
Instead of asking for username, we should ask for Stackoverflow profile ID.

Example: My Stackoverflow profile ID is 9773113. So the expected Dynamic link would be https://stackoverflow.com/users/9773113/ which automatically redirects to my profile.

I'll be happy to make a PR once triage.

**Comment by rahuldkjain** [comment]
@MuhaddiMu I've assigned the issue to you

**Comment by MuhaddiMu** [comment]
@rahuldkjain Please review #26
