### ISSUE TITLE
add conditional rendering of Connect With Me title in social

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#261]
**Is your feature request related to a problem? Please describe.**
Connect with me title is appearing even when there is no social handle is entered.

<img width="367" alt="Screenshot 2020-10-11 at 3 25 45 PM" src="https://user-images.githubusercontent.com/26406279/95675656-7643e500-0bd6-11eb-9ced-f8f2f8eca6ce.png">

**Describe the solution you'd like**
Add a condition to show `Connect with me` title only when there is at least one skill entered.

Join the **Discord Server** for further discussions.

Server Link: https://discord.gg/HHMs7Eg

**Comment by ddaniss** [comment]
I'd like to give it a try

**Comment by kunaljain0212** [comment]
I would like to work on it

**Comment by sarbikbetal** [comment]
Can I work on this?
