### ISSUE TITLE
add issues and pull-requests links in footer under more category

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#263]
**Is your feature request related to a problem? Please describe.**
There is no link to direct the user to open issues and PRs.

**Describe the solution you'd like**
Add issues and pull-requests links in the footer under more category

![Footer](https://user-images.githubusercontent.com/26406279/95676388-65e23900-0bdb-11eb-9081-af2889883e12.png)

Join the **Discord Server** for further discussions.

Server Link: https://discord.gg/HHMs7Eg

**Comment by dalmia007** [comment]
I would like to do this. Can you please assign it to me?

**Comment by rahuldkjain** [comment]
Cool @dalmia007. Please join the discord server for further discussions.

**Comment by dalmia007** [comment]
@rahuldkjain I have already created a pull request for this issue. The PR number is 265

**Comment by rahuldkjain** [comment]
fix by #265.
