### ISSUE TITLE
ES6 syntax for object

### ISSUE THREAD

**Issue by harshcut** [rahuldkjain/github-profile-readme-generator#272]
**Is your feature request related to a problem? Please describe.**
New in JavaScript with ES6/ES2015, if you want to define an object who's keys have the same name as the variables passed-in as properties, you can use the shorthand and simply pass the key name.

Current ES5 Syntax

```javascript
const icons = {
  vuejs: vuejs,
  react: reactjs,
  angularjs: angularjs,
  aws: aws,
  android: android,
  arduino: arduino,
  backbonejs: backbonejs,
  bootstrap: bootstrap,
```

Change to ES6 Syntax

```javascript
const icons = {
  vuejs,
  react,
  angularjs,
  aws,
  android,
  arduino,
  backbonejs,
  bootstrap,
```

**Describe the solution you'd like**
Object Property Value Shorthand in JavaScript with ES6

**Describe alternatives you've considered**
None

**Additional context**
[Example](https://alligator.io/js/object-property-shorthand-es6/#:~:text=New%20in%20JavaScript%20with%20ES6,simply%20pass%20the%20key%20name.)

Join the **Discord Server** for further discussions.

Server Link: https://discord.gg/HHMs7Eg

**Comment by sixthcodebrewer** [comment]
I would like to work on this.

**Comment by harshcut** [comment]
Let @rahuldkjain confirm if this is needed.

**Comment by rahuldkjain** [comment]
Go on @sixthcodebrewer 👍

**Comment by harshcut** [comment]
Closing this issue as it is no longer needed. We have switched back to web hosted URLs.
