### ISSUE TITLE
Yêu cầu tính năng / nâng cao

### ISSUE THREAD

**Issue by hieuhair** [rahuldkjain/github-profile-readme-generator#274]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Join the **Discord Server** for further discussions.

Server Link: https://discord.gg/HHMs7Eg

**Comment by harshcut** [comment]
Closing the issue due to spam.
Is this a mistake? Open a New Issue linking this issue for reference.
