### ISSUE TITLE
bug: no matlab icon link

### ISSUE THREAD

**Issue by YashKandalkar** [rahuldkjain/github-profile-readme-generator#281]
**Describe the bug**
There's matlab in the skills [array of softwares](https://github.com/rahuldkjain/github-profile-readme-generator/blob/dc0f39105abad925d8575b1bda47bc3d2ed24a1f/src/constants/skills.js#L176) but no `matlab` key in the `icons` object.

**To Reproduce**

1. Go to https://rahuldkjain.github.io/gh-profile-readme-generator/
2. Scroll to software section
3. Look at the matlab icon, with no src attribute

**Expected behavior**
An icon (of matlab) to be shown

**Solution**
Add a link to matlab's icon (svg) in the `icons` object in `src/constants/skills.js`

**Screenshots**
![image](https://user-images.githubusercontent.com/35102959/96369626-c68fe980-1178-11eb-9966-3d748453a344.png)

**Desktop (please complete the following information):**

- OS: windows 10 enterprise
- Browser: chrome
- Version: 86.0.4240.75 (Official Build) (64-bit)

Join the **Discord Server** for further discussions.
Server Link: https://discord.gg/HHMs7Eg

**Comment by bhavika24** [comment]
Hi @rahuldkjain,
I would like to work on this. Please assign it to me.

**Comment by YashKandalkar** [comment]
Closing, fixed in #282
