### ISSUE TITLE
add feature to customize the visit-count badge

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#29]
You can provide different input fields after checking `display visitors-count badge` checkbox to customize the badge. 
We can customize the color, style, and label. See below for reference

### Color

You can use any valid HEX color or pick from a predefined set of named colors (`blue` is the default).

| color | demo |
| ----- | ---- |
| `brightgreen` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=44cc11) |
| `green` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=97ca00) |
| `yellow` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=dfb317) |
| `yellowgreen` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=a4a61d) |
| `orange` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=fe7d37) |
| `red` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=e05d44) |
| `blue` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=007ec6) |
| `grey` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=555555) |
| `lightgray` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=9f9f9f) |
| `ff69b4` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=ff69b4) |

**Named color**

```markdown
![](https://komarev.com/ghpvc/?username=your-github-username&color=green)
```

**Hex color**

```markdown
![](https://komarev.com/ghpvc/?username=your-github-username&color=dc143c)
```

> **NOTE**: HEX colors should be used without `#` symbol prefix.

### Styles

The following styles are available (`flat` is the default).

| style | demo |
| ----- | ---- |
| `flat` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=007ec6&style=flat) |
| `flat-square` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=007ec6&style=flat-square) |
| `plastic` | ![](https://img.shields.io/static/v1?label=Profile+views&message=1234567890&color=007ec6&style=plastic) |

```markdown
![](https://komarev.com/ghpvc/?username=your-github-username&style=flat-square)
```

### Label

You can overwrite default `Profile views` text with your own label.

![](https://img.shields.io/static/v1?label=PROFILE+VIEWS&message=1234567890&color=007ec6)

```markdown
![](https://komarev.com/ghpvc/?username=your-github-username&label=PROFILE+VIEWS)
```

> **NOTE**: Replace whitespace with `+` character in multi-word labels.

**Comment by antonkomarev** [comment]
We've released v2 of badge generator package and some changes in colors were added. I recommend to get actual ones from the repository: https://github.com/antonkomarev/github-profile-views-counter#make-it-personal

**Comment by ankitapuri** [comment]
Can you please elaborate what exactly has to be done in this issue ?

**Comment by rahuldkjain** [comment]
add features to customize the shape and color of the badge. Currently, the style of the visitors-count badge is constant. This feature will let users to customize the looks of the badge on their own.

**Comment by antonkomarev** [comment]
It has 3 customizable variables:
- badge style
- background color
- label text

All of them customizable via adding parameters into the query.

**Comment by YashKandalkar** [comment]
Please assign this to me, I'm planning to add a settings icon right next to the question `display visitors count badge`, which will open a popup to customize the badge. If there are any other suggestions, mention me.

**Comment by antonkomarev** [comment]
One minor notice, there is color `lightgray` in the list, I think it will be better to write it `lightgrey` to match the same naming convention as `grey`.
