### ISSUE TITLE
add unit test cases for donate component

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#295]
**Description**
Add a unit test case for the `donate` component

**Describe the solution you'd like**
You can get an idea from the test case written for the `title` component.
```js
import React from "react"
import renderer from "react-test-renderer"

import Title from "../title"

describe("Title", () => {
  it("renders correctly", () => {
    const tree = renderer
      .create(<Title prefix={{ title: "Hi 👋, I'm" }} data={{ title: "" }} />)
      .toJSON()
    expect(tree).toMatchSnapshot()
  })
})
```

**Note**
Add your unit tests in `src/components/__tests__`

Join the **Discord Server** for further discussions.
<a href="https://discord.gg/HHMs7Eg">
<img src="https://discord.com/assets/e4923594e694a21542a489471ecffa50.svg" alt="GPRG Discord Server Link" width="300px"/>
</a>
Server Link: https://discord.gg/HHMs7Eg

**Comment by Citrinin** [comment]
Hello Rahul Jain.
Can I take this one??
Thanks in advance!

**Comment by Citrinin** [comment]
Closed as it's done already.
