### ISSUE TITLE
add feature to customize the github-stats card

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#30]
Please see the README for reference https://github.com/anuraghazra/github-readme-stats

**Comment by rahuldkjain** [comment]
I am integrating the `Top Languages` Card

**Comment by cy** [comment]
Hi! I would like to tackle this.

**Comment by rahuldkjain** [comment]
Cool @cy

**Comment by rahuldkjain** [comment]
Please join the discord server for quick updates.
