### ISSUE TITLE
add unit test cases for work component

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#302]
**Description**
Add a unit test case for the `work` component

**Describe the solution you'd like**
You can get an idea from the test case written for the `title` component.
```js
import React from "react"
import renderer from "react-test-renderer"

import Title from "../title"

describe("Title", () => {
  it("renders correctly", () => {
    const tree = renderer
      .create(<Title prefix={{ title: "Hi 👋, I'm" }} data={{ title: "" }} />)
      .toJSON()
    expect(tree).toMatchSnapshot()
  })
})
```

**Note**
Add your unit tests in `src/components/__tests__`

Join the **Discord Server** for further discussions.
<a href="https://discord.gg/HHMs7Eg">
<img src="https://discord.com/assets/e4923594e694a21542a489471ecffa50.svg" alt="GPRG Discord Server Link" width="300px"/>
</a>
Server Link: https://discord.gg/HHMs7Eg

**Comment by VeenaDesai38** [comment]
@rahuldkjain I would like to take up the task of adding unit tests to the components mentioned in the issues.

**Comment by rahuldkjain** [comment]
Cool @VeenaDesai38. You can join our discord server for quick discussions and updates related to the project.

**Comment by VeenaDesai38** [comment]
sure. thanks.
@rahuldkjain Here is the PR adding unit tests for work component https://github.com/rahuldkjain/github-profile-readme-generator/pull/307
I also modified title.test.js to bring thee coverage to 100%. Let me know you thoughts on this.
<img width="613" alt="Screen Shot 2020-10-23 at 10 34 43 PM" src="https://user-images.githubusercontent.com/73214669/97033083-66d27d80-1580-11eb-806b-5f688b944f9d.png">

**Comment by rahuldkjain** [comment]
Superb @VeenaDesai38
