### ISSUE TITLE
Logos returning an ERROR 404.

### ISSUE THREAD

**Issue by Akshat1305** [rahuldkjain/github-profile-readme-generator#31]
**Describe the bug**
The image logos under skills are returning an ERROR 404 (Page not found).

**To Reproduce**
1. Go to https://konpa.github.io/devicon/devicon.git/icons/react/react-original-wordmark.svg
2. See error

**Screenshot**
https://rahuldkjain.github.io/gh-profile-readme-generator/

![Capture](https://user-images.githubusercontent.com/63666629/88368454-bfd91c80-cdab-11ea-9de3-8864295160ee.PNG)

**Comment by rahuldkjain** [comment]
@Akshat1305 thanks for informing.
The developer renamed the repository from `https://konpa.github.io` to `https://devicons.github.io`. Will fix this asap

**Comment by rahuldkjain** [comment]
Fixed
