### ISSUE TITLE
Make tests rely on one testing library

### ISSUE THREAD

**Issue by Citrinin** [rahuldkjain/github-profile-readme-generator#322]
**Describe the bug**
After mergin this PR https://github.com/rahuldkjain/github-profile-readme-generator/pull/307 we add `enzyme` testing library and remove `react-test-rederer`. After it all other tests stop working because they continue to rely on it. So I think it's worth to update it and refactor a little bit.

**Expected behavior**
All the tests works.

**Comment by Citrinin** [comment]
I'd like to work on this issue.

**Comment by Citrinin** [comment]
Will be fixed by https://github.com/rahuldkjain/github-profile-readme-generator/pull/321

**Comment by rahuldkjain** [comment]
@Citrinin it will be easy to discuss if you join the discord server.
