### ISSUE TITLE
No images in skills

### ISSUE THREAD

**Issue by chsanleo** [rahuldkjain/github-profile-readme-generator#33]
Hi!
In the generator u can see correctly all the images of the skills but when u use the code in ur readme doesn't show it.

![imagen](https://user-images.githubusercontent.com/65183792/88415886-89b59000-cddf-11ea-9f28-1e5672a31c4d.png)

Looks like the links for the images return a 404, I add some links of that img src:
https://konpa.github.io/devicon/devicon.git/icons/angularjs/angularjs-original.svg
https://konpa.github.io/devicon/devicon.git/icons/html5/html5-original-wordmark.svg
https://konpa.github.io/devicon/devicon.git/icons/laravel/laravel-plain-wordmark.svg

In previous versions the images are storage in another links and works perfectly:

https://camo.githubusercontent.com/4781e0847a4467c26c793b583a64dac8c15007bf/68747470733a2f2f64657669636f6e732e6769746875622e696f2f64657669636f6e2f64657669636f6e2e6769742f69636f6e732f616e67756c61726a732f616e67756c61726a732d6f726967696e616c2e737667
https://camo.githubusercontent.com/5712bffd0347cc2744de599dc54473dc1ebbfe82/68747470733a2f2f64657669636f6e732e6769746875622e696f2f64657669636f6e2f64657669636f6e2e6769742f69636f6e732f637373332f637373332d6f726967696e616c2d776f72646d61726b2e737667
https://camo.githubusercontent.com/9599dc988280bea2ca5c44c4796f13494f9ff3f7/68747470733a2f2f64657669636f6e732e6769746875622e696f2f64657669636f6e2f64657669636f6e2e6769742f69636f6e732f68746d6c352f68746d6c352d6f726967696e616c2d776f72646d61726b2e737667

thanks!

**Comment by ankurchaudhary627** [comment]
This issue has already been raised [here](https://github.com/rahuldkjain/github-profile-readme-generator/issues/31) and fixed [here](https://github.com/rahuldkjain/github-profile-readme-generator/commit/2153a7ac6e3f913cf6a0e3304b3ac7dc100a9b6f). You might need to generate the readme again.

**Comment by chsanleo** [comment]
ok! thanks!
