### ISSUE TITLE
Add new skills 

### ISSUE THREAD

**Issue by chsanleo** [rahuldkjain/github-profile-readme-generator#34]
Can Add new skills with the icon? 
like=>
 
Spring:
https://spring.io/images/spring-logo-9146a4d3298760c2e7e49595184e1975.svg
Matlab:
https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Matlab_Logo.png/240px-Matlab_Logo.png
Kotlin:
https://res.cloudinary.com/vlctechhub/image/twitter_name/w_350/kotlin_es.jpg

**Comment by rahuldkjain** [comment]
@chsanleo would you like to work on this?

**Comment by chsanleo** [comment]
Yes of course

**Comment by Maddoxx88** [comment]
Can I contribute in adding more skills and their eventual PNG/SVG files?
@chsanleo @rahuldkjain

**Comment by Maddoxx88** [comment]
Like in many frameworks, databases and more. Or can I create a pull request directly?

**Comment by rahuldkjain** [comment]
@Maddoxx88 you can create a PR referring to this issue. I am assigning the issue to you

**Comment by Maddoxx88** [comment]
Ohk
