### ISSUE TITLE
Contact me icons are "invisible" on dark theme

### ISSUE THREAD

**Issue by marimeireles** [rahuldkjain/github-profile-readme-generator#345]
Hey, with the new github dark theme the black icons get invisible almost.
Would be nice to be able to tweak their colors, or better yet, use a default that will show up in both themes.
I'd suggest the blue color that github uses for links and stuff.
Lemme know what you think about it. I can open a PR making this change, cheers!

**Comment by rahuldkjain** [comment]
Thanks @marimeireles for opening this issue. It would be great if you could open a PR for the same 🙇‍♂️.

**Comment by marimeireles** [comment]
What's a good approach for this?
Painting the icons blue?
I'm not very knowledgeable on CSS but I think there is a `media` option that allows you to get the theme from the page, and that'd allow us to create something dynamic. But again, idk much about it and also not sure about the interactions with MD.

**Comment by rahuldkjain** [comment]
@marimeireles we need to pick theme neutral icons to solve this issue.

**Comment by jaygandhi129** [comment]
Facing the same issue......Any fixes?

**Comment by chandrikadeb7** [comment]
@rahuldkjain Can I work on this?

**Comment by rahuldkjain** [comment]
@chandrikadeb7 Yeah sure 💯
