### ISSUE TITLE
images are not able to loaded in the website

### ISSUE THREAD

**Issue by saitharunsai** [rahuldkjain/github-profile-readme-generator#350]
[**Describe](https://rahuldkjain.github.io/gh-profile-readme-generator/) the bug**

**To Reproduce**

1. Go to 'website'
2. See error
3. change the devicon links to get reflected

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![Screenshot (68)](https://user-images.githubusercontent.com/65693649/103469988-1fdbe200-4d92-11eb-8c75-52b159d54793.png)
![Screenshot (69)](https://user-images.githubusercontent.com/65693649/103469989-210d0f00-4d92-11eb-8f5a-eaaa36e5a827.png)

Join the **Discord Server** for further discussions.

<a href="https://discord.gg/HHMs7Eg">
<img src="https://discord.com/assets/e4923594e694a21542a489471ecffa50.svg" alt="GPRG Discord Server Link" width="300px"/>
</a>

Server Link: https://discord.gg/HHMs7Eg

**Comment by rahuldkjain** [comment]
@saitharunsai  the cdn image url for devicon have changed.
Would you like to solve this bug?

**Comment by saitharunsai** [comment]
yes
