### ISSUE TITLE
Images don't appear

### ISSUE THREAD

**Issue by EliazBobadilla** [rahuldkjain/github-profile-readme-generator#351]
**Describe the bug**
Images don't appear

**To Reproduce**
Go to https://rahuldkjain.github.io/gh-profile-readme-generator/ or my Readme repo and see.

**Expected behavior**
I expect to see the images.

**Screenshots**
![image](https://user-images.githubusercontent.com/71897736/103470795-0fe9e100-4d45-11eb-83de-1bc5a307b638.png)
![image](https://user-images.githubusercontent.com/71897736/103470801-242dde00-4d45-11eb-99a7-5f24aa1b2a86.png)
![image](https://user-images.githubusercontent.com/71897736/103470805-2c861900-4d45-11eb-85a9-c8e382cbd02f.png)
![image](https://user-images.githubusercontent.com/71897736/103470808-3445bd80-4d45-11eb-9518-7552e5454e4b.png)
![image](https://user-images.githubusercontent.com/71897736/103470809-39a30800-4d45-11eb-97c1-99df83215e62.png)
![image](https://user-images.githubusercontent.com/71897736/103470811-40317f80-4d45-11eb-87cc-1fd1e332ab86.png)
![image](https://user-images.githubusercontent.com/71897736/103470815-458eca00-4d45-11eb-8236-74d7f8331cdc.png)
![image](https://user-images.githubusercontent.com/71897736/103470817-49225100-4d45-11eb-9b15-b49def6214d2.png)
![image](https://user-images.githubusercontent.com/71897736/103470819-4de70500-4d45-11eb-94e5-25210cf20786.png)

**Desktop (please complete the following information):**

- OS: Fedora WorkStation,my cellphone and my tv.
- Browser:Chrome and the native android app of GitHub.
- Version :
![image](https://user-images.githubusercontent.com/71897736/103470829-8c7cbf80-4d45-11eb-9d40-9efde91452f0.png)

**Comment by EliazBobadilla** [comment]
> Thanks for opening your first issue here! Your contribution means alot.  Join Discord Server (https://discord.gg/HHMs7Eg) for discussing issues, pull-requests, new features, etc.

I don't use Discord uwun't.

**Comment by Su-Kyung** [comment]
I've the same issue. Image link path seems to be wrong. Do I have to solve it in my personal repo?

**Comment by Vishal1297** [comment]
I too have the same issue.

**Comment by rahuldkjain** [comment]
@Vishal1297 @Su-Kyung @EliazBobadilla the cdn image url for devicon have changed. I am solving this issue

**Comment by parasg1999** [comment]
Can I take this up? @rahuldkjain 
Can use the github repo link for the icons, like https://github.com/devicons/devicon/blob/master/icons/go/go-original.svg for Go

**Comment by rahuldkjain** [comment]
Hey @parasg1999 thanks for taking interest. I've assigned this issue to @saitharunsai. You can pick up any other open issues.

**Comment by advaithm** [comment]
based on some quick editing you can replace `https://devicons.github.io/devicon/devicon.git` with  `https://github.com/devicons/devicon/blob/master/` and the icons show up again

**Comment by Su-Kyung** [comment]
> based on some quick editing you can replace `https://devicons.github.io/devicon/devicon.git` with `https://github.com/devicons/devicon/blob/master/` and the icons show up again

It is simple and works pretty well. Thanks :-)

**Comment by saitharunsai** [comment]
This issue has fixed @Su-Kyung

**Comment by diiegoburiti** [comment]
> based on some quick editing you can replace `https://devicons.github.io/devicon/devicon.git` with `https://github.com/devicons/devicon/blob/master/` and the icons show up again

Nice, it works for me.

**Comment by EliazBobadilla** [comment]
Ok.
