### ISSUE TITLE
Contribution graph option can be added too

### ISSUE THREAD

**Issue by Ashutosh00710** [rahuldkjain/github-profile-readme-generator#359]
**Describe the solution you'd like**
I have created a readme project [github-readme-activity-graph](https://github.com/Ashutosh00710/github-readme-activity-graph) which will show your recent GitHub activity (contributions) with a attractive graph SVG.

**Link to the repository:** https://github.com/Ashutosh00710/github-readme-activity-graph

**Additional context**
Demo/Example:

[![Ashutosh's github activity graph](https://github-readme-activity-graph.cyclic.app/graph?username=rahuldkjain&&theme=rogue&area=true)](https://github.com/ashutosh00710/github-readme-activity-graph)

**Comment by harikanani** [comment]
@chaitanyasjoshi , i would like to work on this issue can you please assign it to me so that, i can start working on it.

**Comment by Ashutosh00710** [comment]
@rahuldkjain can you please review this.
