### ISSUE TITLE
Add a blank line after <h3> tag

### ISSUE THREAD

**Issue by scottcwilson** [rahuldkjain/github-profile-readme-generator#36]
The output of the generator needs to put a blank line between the subtitle and the first Work entry ("I'm currently working on.")  Otherwise, the links in the first Work entry will not work; you'll just see them displayed as raw Markdown.  (In Github markdown you have to have a blank line between HTML and Markdown, or the Markdown won't be interpreted.)

**Comment by rahuldkjain** [comment]
Thanks, @scottcwilson :bowing_man: for opening the bug. 
It has been fixed by https://github.com/rahuldkjain/github-profile-readme-generator/pull/37

**Comment by scottcwilson** [comment]
Great job on the tool!  Thank you.

**Comment by rahuldkjain** [comment]
Received my first ever grant on the OSS 🙏. That's so sweet of you.

A big thanks @scottcwilson 🙇

**Comment by scottcwilson** [comment]
Many moons ago, my business started the same way - due to the generosity of someone who appreciated my work.  Good luck in your journey.
