### ISSUE TITLE
[BUG]  Under Social section Github link container is only accepting lowercase values

### ISSUE THREAD

**Issue by Ashray123** [rahuldkjain/github-profile-readme-generator#364]
**Describe the bug**
After adding a link to my Github profile, I noticed that my username's first alphabet is changed from upper case to lower case which leads to an error while submitting the form. 

**To Reproduce**

1. Scroll down to the Social section 
2. Try adding a GitHub link of username containing at least an Uppercase alphabet.
3. Scroll below and you will see that error is displayed.
**Expected behavior**
Github username container should also accept uppercase values.
**Screenshots**

https://user-images.githubusercontent.com/40429213/107884408-ee227300-6f1a-11eb-9a0c-a9903f5926a6.mov

**Desktop (please complete the following information):**

- OS: Mac os
- Browser :Chrome

**Comment by chaitanyasjoshi** [comment]
I just checked and it seems that all containers under social section except discord are only accepting lowercase values.
@Ashray123 check the same and consider updating the issue topic.

**Comment by harikanani** [comment]
for GitHub, both upper case and lower case are the same. there is no case sensitivity for github profile link
for ex:
https://github.com/ASHRAY123
https://github.com/Ashray123
https://github.com/ashray123

above all links are the same and redirect to your Github profile.
so, I request @chaitanyasjoshi to close this issue asap!

**Comment by rahuldkjain** [comment]
Yep there is no need to make that case sensitive

**Comment by Ashray123** [comment]
@rahuldkjain I also agree with "@harikanani" but that is not the case here .. I am still getting the error while submitting and you can check the video that I have added in the description of the issue. If my alphabets are turned to lower case , your form is not able to detect my GitHub id. Please go ahead and let me know where I am mistaken.

**Comment by rahuldkjain** [comment]
@Ashray123 If you see carefully, the error message is suggesting you to enter the username only, not the entire url.

**Comment by harikanani** [comment]
> @Ashray123 If you see carefully, the error message is suggesting you to enter the username only, not the entire url.

Yes!
