### ISSUE TITLE
PayPal icon link broken

### ISSUE THREAD

**Issue by chaitanyasjoshi** [rahuldkjain/github-profile-readme-generator#365]
The link to the PayPal icon in support section is broken

1. Go to 'Home page'
2. Click on 'Generate README'
3. Scroll down to 'Support section'
4. Missing PayPal icon

**Expected behavior**
PayPal icon should be displayed properly

**Screenshots**
![Capture](https://user-images.githubusercontent.com/23653544/108244063-c4fd1f00-7174-11eb-8042-66a400b38dc0.PNG)

**Comment by harikanani** [comment]
@chaitanyasjoshi can you assign me this task I'll start working on it

**Comment by harikanani** [comment]
@rahuldkjain , Please Check My PR #366 that resolves this issue and close this issue asap!

**Comment by chaitanyasjoshi** [comment]
PR #366  solves the issue.

**Comment by chandrikadeb7** [comment]
I think this issue is still persisting.
![Screenshot 2021-04-03 at 12 34 19 AM](https://user-images.githubusercontent.com/29686102/113445948-659d5a80-9414-11eb-8941-9782e6de5d19.png)
