### ISSUE TITLE
Incorrect spelling of "regularly"

### ISSUE THREAD

**Issue by aravindvnair99** [rahuldkjain/github-profile-readme-generator#369]
The following files have the misspelling:

- [markdown.test.js.snap](https://github.com/rahuldkjain/github-profile-readme-generator/tree/master/src/components/__tests__/__snapshots__/markdown.test.js.snap)
- [markdownPreview.test.js.snap](https://github.com/rahuldkjain/github-profile-readme-generator/tree/master/src/components/__tests__/__snapshots__/markdownPreview.test.js.snap)
- [markdown.test.js](https://github.com/rahuldkjain/github-profile-readme-generator/tree/master/src/components/__tests__/markdown.test.js)
- [markdownPreview.test.js](https://github.com/rahuldkjain/github-profile-readme-generator/tree/master/src/components/__tests__/markdownPreview.test.js)

There was a commit previously to fix [the typo](https://github.com/rahuldkjain/github-profile-readme-generator/commit/ec78c6ba0534beec8ff4915f94d0e9adbd199b5c#diff-26ca35c3be6d07c84bb77f1e63a1b19487279d5b9c9a9392179b3a35647e1254L45) in a commit [here](https://github.com/rahuldkjain/github-profile-readme-generator/commit/ec78c6ba0534beec8ff4915f94d0e9adbd199b5c#diff-2715e47e84094ab6a942260599168f35875404bea9e9c38760595e94528ab2aaR12). I assume the test cases got missed out.

**Comment by rahuldkjain** [comment]
This is fixed in the recent release.

**Comment by aravindvnair99** [comment]
> This is fixed in the recent release.

@rahuldkjain It isn't a duplicate. The main code was fixed in the commit I referenced. But the tests weren't fixed. That's what this issue and my linked PR is for.
