### ISSUE TITLE
Add SupaBase as BaaS 

### ISSUE THREAD

**Issue by apoorvcodes** [rahuldkjain/github-profile-readme-generator#421]
I will suggest to add SupaBase as BaaS, as its a very good alternative to Firebase, if you can explain me some of the code structure, I can add it and do a pull  request

**Comment by rahuldkjain** [comment]
Nice idea @apoorvcodes.

**Comment by apoorvcodes** [comment]
I can help adding it just specify how the project works :D

**Comment by Bartek532** [comment]
Is it still open? I would work on it 😁
