### ISSUE TITLE
Buy me a coffe username does not gets saved in json

### ISSUE THREAD

**Issue by Y0ngg4n** [rahuldkjain/github-profile-readme-generator#423]
**Describe the bug**
If you enter your buymeacoffe username in the field and generate a readme it did not get saved in the backup json.

**To Reproduce**

1. Enter your buymeacoffe username
2. Generate Readme
3. Download backup
4. Upload backup
5. bymeacoffe does not gets restored

**Expected behavior**
Restored bymeacoffe username

**Comment by gargipandkar** [comment]
Could this issue be assigned to me?
Quick fix - I've it ready to raise PR
