### ISSUE TITLE
Bug : nextjs icon is not showing

### ISSUE THREAD

**Issue by yarncha** [rahuldkjain/github-profile-readme-generator#438]
**Describe the bug**
[website](https://rahuldkjain.github.io/gh-profile-readme-generator/)'s Skills-Static Site Generators section, next js icon seems broken and the url of img is not found.

**To Reproduce**
1. Go to [website](https://rahuldkjain.github.io/gh-profile-readme-generator/)
2. On _Skills - Static Site Generators_ section, there is next js icon

**Expected behavior**
an icon of next js should be shown

**Screenshots**
![image](https://user-images.githubusercontent.com/33623182/134812035-85647451-04c6-4177-b9fe-792b4db8a604.png)

**Desktop (please complete the following information):**
- OS : Window 10
- Browser : chrome

**Comment by rahuldkjain** [comment]
<img width="1166" alt="Screenshot 2021-09-26 at 8 02 35 PM" src="https://user-images.githubusercontent.com/26406279/134812204-1594f878-8a7d-4e21-b315-a56c5164af0e.png">
It's coming fine.

**Comment by yarncha** [comment]
Thank you for your quick response! But that icon still doesn't look error-free to me....😢

![image](https://user-images.githubusercontent.com/33623182/134812367-12ff7c90-c601-446b-926b-19572996bb58.png)
It is a screen that pops up when i access [that icon's source](https://cdn.worldvectorlogo.com/logos/nextjs-3.svg)
Will this help to fix this error...?

**Comment by HristovCodes** [comment]
It renders fine for me as well. Can you try a different browser perhaps? Also does this happen every time or did it happen when you loaded the page and you didn't try refreshing (with ctrl+f5)?

**Comment by yarncha** [comment]
Oh I found the same issue #378

**Comment by HristovCodes** [comment]
Perhaps your firewall is blocking that source, or maybe even your isp which would be even weirder?

**Comment by yarncha** [comment]
> Perhaps your firewall is blocking that source, or maybe even your isp which would be even weirder?

Looking at other people's cases, I'm also guessing that the reason for this problem is not the code, but that blocking. Then, would it be better to close this issue?

**Comment by HristovCodes** [comment]
> > Perhaps your firewall is blocking that source, or maybe even your isp which would be even weirder?
> 
> Looking at other people's cases, I'm also guessing that the reason for this problem is not the code, but that blocking. Then, would it be better to close this issue?

I would assume so. It's not a problem with the actual code.

**Comment by rahuldkjain** [comment]
I think there is an SVG support issue with some devices/browser
