### ISSUE TITLE
Refactor all icons to neutral SVGs (Stackoverflow, Codeforces, etc.)

### ISSUE THREAD

**Issue by chandrikadeb7** [rahuldkjain/github-profile-readme-generator#444]
Some of the existing icons are not visible with GitHub dark theme. 
For example, icons in src/images/Social --- Stackoverflow, Codeforces, etc.

We can use neutral coloured SVGs for all the icons which are not yet updated.

**Comment by chandrikadeb7** [comment]
@rahuldkjain I would like to work on this issue.

**Comment by rahuldkjain** [comment]
Cool.
Please take care of few things here:
1. Use SVG icons wherever possible
2. Optimise the SVG icons using this [SVGOMG](https://jakearchibald.github.io/svgomg/) tool.

I just realized that the file size of Dev[.]to SVG is 324KB 🤯. Please optimize this file too.

Thanks 🚀
