### ISSUE TITLE
Better checkboxes design for skills

### ISSUE THREAD

**Issue by DmnChzl** [rahuldkjain/github-profile-readme-generator#457]
Hello again 👋
It would be great to have more stylish checkboxes!
Why not... toggle switches instead? 🤔

**Comment by suprabhat25** [comment]
Can you assign this issue to me?

**Comment by logicalahara** [comment]
Hey @MrDoomy, this seems to be a nice redesign and I'd like to contribute to this issue.

I developed [https://eumentis.com](url) and having a grip on gatsby

**Comment by MrDoomy** [comment]
Hi guys 👋
I've already pushed something here [#458](https://github.com/rahuldkjain/github-profile-readme-generator/pull/458)
I'm waiting for a review...
