### ISSUE TITLE
Add categories in skills

### ISSUE THREAD

**Issue by saianurag2** [rahuldkjain/github-profile-readme-generator#46]
**Is your feature request related to a problem? Please describe.**
As the skill list keeps growing, it makes sense to categorise the skills

**Describe the solution you'd like**
Categories based on Utility. 
Frontend, Backend, Frameworks(could be clubbed with f/e or b/e), Databases, Tools(eg: Git, Meld, Postman), Testing
**Describe alternatives you've considered**
Add custom-order for listed skills. The order of listing the skills is another option where the proficiency in skills decrease as we reach the end of the list.

**Comment by rahuldkjain** [comment]
I think categorizing the skills based on their utility (like AI/ML, Frontend, Backend, Database, etc) instead of experience and proficiency will be more beneficial @saianurag2

**Comment by saianurag2** [comment]
I agree with your suggestion. I will update my issue.
