### ISSUE TITLE
Animated Github Badges

### ISSUE THREAD

**Issue by acervenky** [rahuldkjain/github-profile-readme-generator#50]
**Is your feature request related to a problem? Please describe.**
Recently the Arctic Contributor Badge has been added to our github profiles, this is a way of integrating it in our reamde profiles as well.

**Describe the solution you'd like**
Minimalistic icons with animations rendered in AE, will go well with the overall theme of your generator.

**Describe alternatives you've considered**
I can provide static icons if required.

**Additional context**
Badge Preview On My Profile : [acervenky](https://github.com/acervenky)
Badge Repo : [animated-github-badges](https://github.com/acervenky/animated-github-badges)

**Comment by priyanshnama** [comment]
@rahuldkjain can you assign this to me.
@acervenky  can you provide with static icons

**Comment by rahuldkjain** [comment]
Not needed this as of now.
