### ISSUE TITLE
Margin between Most Used Languages and GitHub Stats to prettify things

### ISSUE THREAD

**Issue by somikdatta** [rahuldkjain/github-profile-readme-generator#52]
**Problem:** On narrower screen real estate, Most Used Languages card and GitHub Stats card pile on top of each other.

**Solution:** Add top margin on both the cards.

_I'd be more than happy to make this happen with my contribution_

**Preview 1 - 1366px width**
![Preview 1 - 1366px width](https://user-images.githubusercontent.com/51878110/89536401-7958d880-d815-11ea-9e06-3f2e8780760c.png)
**Preview 2 - mobile width**
![Preview 2 - mobile width](https://user-images.githubusercontent.com/51878110/89536509-a2796900-d815-11ea-8257-861a236007f7.jpeg)

**Comment by rahuldkjain** [comment]
@somikdatta would you like to fix that?

**Comment by somikdatta** [comment]
Of course, would be glad to be of help!

**Comment by somikdatta** [comment]
@rahuldkjain Of course, would be glad to be of help!
