### ISSUE TITLE
Unable to generate skill icon

### ISSUE THREAD

**Issue by ChenYu-K** [rahuldkjain/github-profile-readme-generator#565]
**Describe the bug**

Unable to generate skill icon

I can't generate the skill icon, is there a necessary condition to generate the icon?
Only icons cannot be generated
Regardless of using `Chrome`, `Edge`, and `Localhost` all can not be generated.

- OS: [Winsow11]
- Browser [chrome]

**Comment by rudkul** [comment]
Having the same issue here. Not able to generate the markdown for the skills. Everything else seems to be working fine.

**Comment by Ajit-91** [comment]
Having same issue rest is working fine but skills are not being added in the markdown for some reason

**Comment by rahuldkjain** [comment]
Shit, anyone wants to take this up & fix?

**Comment by rahuldkjain** [comment]
This was critical, so I personally fixed it.
Thanks for the awareness 👏
