### ISSUE TITLE
Add title to the languages and tools listed on the profile

### ISSUE THREAD

**Issue by ExploreWithCode** [rahuldkjain/github-profile-readme-generator#582]
## Just add the title attribute like this:  title="HTML"

<h3 align="left">Languages and Tools:</h3>
<p align="left">
  <a href="https://en.wikipedia.org/wiki/HTML" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" title="HTML" width="40" height="40"/> </a>
  </p>

 ### Here is the code:
```
<h3 align="left">Languages and Tools:</h3>
<p align="left">
  <a href="https://en.wikipedia.org/wiki/HTML" target="_blank"> <img src="https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original-wordmark.svg" alt="html5" title="HTML" width="40" height="40"/> </a>
  </p>

**Comment by agkeshav** [comment]
Hey I can do this well and also understand well what you need.
Please give me this issue to solve.

**Comment by ExploreWithCode** [comment]
> Hey I can do this well and also understand well what you need. Please give me this issue to solve.

I have no idea how to contribute.

**Comment by agkeshav** [comment]
> 

may be there is some problem from github itself you can try assigning again. Actually I am very new to open source so I do not know much about it
