### ISSUE TITLE
Hashnode logo in Social is Wrong.

### ISSUE THREAD

**Issue by abhishekrd** [rahuldkjain/github-profile-readme-generator#616]
- The logo for Hashnode in the social section is wrong. It is not the Hashnode logo.
- ![Screenshot 2022-10-04 110655](https://user-images.githubusercontent.com/88556842/193743360-bdae3c34-6f1f-4b39-a0fd-253e8e63bd16.png)
- I want to replace this logo with the real Hashnode logo
@rahuldkjain can you please assign this to me?

**Comment by JatinSingh08** [comment]
Hey @abhishekrd, please assign this issue to me.

**Comment by abhishekrd** [comment]
@rahuldkjain can you please assign this issue to me?
