### ISSUE TITLE
[Addition of new skills - Under existing categories]

### ISSUE THREAD

**Issue by Hardik0307** [rahuldkjain/github-profile-readme-generator#62]
Hello :wave:,
Want to **add some skills** like Hugo(under static site), CanvasJS(Data Visualization).

and all are in SVG format itself.

Ready with name + icons.
@utsav00 also wants to contribute more skills.

**Comment by utsav00** [comment]
Hey, I'd love to contribute to this project by adding some skills such as some Database tools and some programming languages.
