### ISSUE TITLE
Add notification on the Reset button

### ISSUE THREAD

**Issue by ashrafchowdury** [rahuldkjain/github-profile-readme-generator#659]
There is no alert notification when the user resets the form.

If we add an alert notification on the Reset-form button, this will be good for the user.

**Comment by ashrafchowdury** [comment]
I would like to add an alert notification on the Reset button.

**Comment by shivamshahi07** [comment]
I would be very happy to contribute to this project by working on this issue. 
Please assign me this issue.
Thanks
