### ISSUE TITLE
Add Datastructures and algorithms under skills

### ISSUE THREAD

**Issue by g-savitha** [rahuldkjain/github-profile-readme-generator#66]
Add problem solving skills category
and also add social links of hackerrank, leetcode, spoj, codechef etc.

**Comment by rahuldkjain** [comment]
Would you like to work on this @g-savitha ?

**Comment by github-contributor-1** [comment]
@rahuldkjain I want to work on adding social links of hackerrank, leetcode, codechef  etc

**Comment by rahuldkjain** [comment]
@amruta-kashikar great. I've assigned the issue to you.

**Comment by g-savitha** [comment]
hey i have already done that part and raised a PR https://github.com/rahuldkjain/github-profile-readme-generator/pull/82

**Comment by g-savitha** [comment]
@amruta-kashikar i have added for hackerrank, hackerearth, gfg and leetcode. You can add for others like codechef, interviewbit, spoj, topcoder etc

**Comment by amruta-kashikar** [comment]
@g-savitha I have no problem but it is assigned by @rahuldkjain , so you just ask him

**Comment by g-savitha** [comment]
LOL

**Comment by rahuldkjain** [comment]
> hey i have already done that part and raised a PR #82

@rahuldkjain Please make sure that the issue gets assigned to you before start working. Really appreciate your efforts 😁
