### ISSUE TITLE
Spelling Typo

### ISSUE THREAD

**Issue by leonardsangoroh** [rahuldkjain/github-profile-readme-generator#684]
**Describe the bug**
There's a grammatical or spelling error under the 'work' sub-section
Instead of " I'm looking to collaborate.." it states " I'm looking to collaborat"
There is no "e" at the end

**To Reproduce**
Just load the site and navigate to the "Work" subsection, you will see the spelling error

**Screenshots**
![Screenshot 2023-01-29 at 12 26 01](https://user-images.githubusercontent.com/61079370/215317284-d2f53666-aaf6-4a20-8f46-e39ded65c565.png)

**Desktop (please complete the following information):**

- OS: Mac OS Moneterey
- Browser : Safari
- Version : 15.2

**Comment by tmsagarofficial** [comment]
Can i work on this @leonardsangoroh @rahuldkjain

**Comment by leonardsangoroh** [comment]
@rahul is the one with assigning you the issue. I just raised the issue

Kind regards,
Leonard Sangoroh

**Comment by tmsagarofficial** [comment]
yeah @rahuldkjain pls look about this and assign it to me if possible

**Comment by love-sonkar** [comment]
i think this issue is fixed because im not able to find the issue

**Comment by leonardsangoroh** [comment]
> i think this issue is fixed because im not able to find the issue

Thank you for the notification. Yes, the issue is fixed. I am closing this issue as it has been resolved.
