### ISSUE TITLE
NOT working GitHub Pages 

### ISSUE THREAD

**Issue by ChintzRuparel** [rahuldkjain/github-profile-readme-generator#689]
**Describe the bug**
Not working GitHub Pages 

**To Reproduce**
https://rahuldkjain.github.io/gh-profile-readme-generator/

**Expected behavior**

**Screenshots**
<img width="1440" alt="Screenshot 2023-02-11 at 21 19 37" src="https://user-images.githubusercontent.com/51440734/218267645-b7a59759-74cb-4eea-83fa-4315f59fdc99.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Join the **Discord Server** for further discussions.

<a href="https://discord.gg/HHMs7Eg">
<img src="https://discord.com/assets/e4923594e694a21542a489471ecffa50.svg" alt="GPRG Discord Server Link" width="300px"/>
</a>

Server Link: https://discord.gg/HHMs7Eg

**Comment by ChintzRuparel** [comment]
Error in Preview and not in Production
Will be great if you can change the website in the homepage

**Comment by Yuchen-Wang-SH** [comment]
> Error in Preview and not in Production Will be great if you can change the website in the homepage

Hey, where is the Production?

**Comment by ChintzRuparel** [comment]
@Yuchen-Wang-SH The error is in preview (deployed through GitHub Pages)
I will link it below 

https://rahuldkjain.github.io/gh-profile-readme-generator/

Cheers 🥂

**Comment by rahuldkjain** [comment]
It's up and running now, sorry for the inconvenience.
