### ISSUE TITLE
display dynamic counts with star and fork button in header

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#7]
![Screenshot_2020-07-19 Github Profile Readme Generator](https://user-images.githubusercontent.com/26406279/87866986-f971e800-c9a5-11ea-99b9-dcb07a15c3e7.png)

These buttons in the header should display their respective dynamic counts

**Comment by abhijit-hota** [comment]
Can I work on this?

**Comment by ankurchaudhary627** [comment]
Can you please elaborate on this issue? I didn't get this one. @rahuldkjain

**Comment by rahuldkjain** [comment]
@ankurchaudhary627 showing stars count in star this repo button and forks count in fork on github button

**Comment by abhijit-hota** [comment]
@rahuldkjain I'm having some issues using `useEffect` as I'm not experienced in it. Can I convert the `src/components/header.js` to a stateful class component and use `componentDidUpdate` instead?


P.S. I need to make an API call to GitHub API.

**Comment by ankurchaudhary627** [comment]
I was looking into this, can you assign this to me it might be worth saving time to convert the file to class component. I am going to use useEffect.

**Comment by rahuldkjain** [comment]
> @rahuldkjain I'm having some issues using `useEffect` as I'm not experienced in it. Can I convert the `src/components/header.js` to a stateful class component and use `componentDidMount` instead?
> 
> P.S. I need to make an API call to GitHub API.

@ankurchaudhary627 is working on this. You can pick some other issues.

**Comment by rahuldkjain** [comment]
You can use buttons from https://buttons.github.io/

**Comment by ankurchaudhary627** [comment]
@rahuldkjain I explored github buttons. There are 2 issues in using that, first github button's UI is different from what is already there in the code right now. Secondly, the github button provides static count of stars and forks, and we don't have control to update those. 
Right now I'm fetching from github api, and the update is happening dynamically, but there is delay which I'm trying to reduce.
The UI is like this after my changes:
![image](https://user-images.githubusercontent.com/27446217/87956747-05a49500-cacd-11ea-9351-c1c18049a18b.png)
There is some css needs to be updated though!

**Comment by rahuldkjain** [comment]
I've used the buttons before, but removed it to make UI clean. You can go with your approach

**Comment by ankurchaudhary627** [comment]
I see it takes around 40-45 seconds to update the count state, after it's been updated on Github. If that's fine? @rahuldkjain

**Comment by rahuldkjain** [comment]
@ankurchaudhary627 40-45 seconds is too much. If it doesn't work then we will have to use the buttons mentioned above

**Comment by ankurchaudhary627** [comment]
Okay, I will see how I can reduce it, and let you know! @rahuldkjain

**Comment by rahuldkjain** [comment]
@ankurchaudhary627 any update?

**Comment by ankurchaudhary627** [comment]
Hi @rahuldkjain , so the issue is with the github api. There's limit on the api calls that we can make with github api. For, getting more number of requests we need to make Oauth get requests. 
Right now, i am fetching every 15 seconds to get the updated count for stars and forks.

**Comment by ankurchaudhary627** [comment]
How can we do the same with the buttons that you mentioned earlier, its giving static count, right? Plus the UI is different from what is there currently

**Comment by rahuldkjain** [comment]
I've used them here https://rahuldkjain.github.io

Its pretty straightforward and I think it won't affect the UI much

**Comment by ankurchaudhary627** [comment]
Isn't the button used there different from this
![image](https://user-images.githubusercontent.com/27446217/88081682-5d5f0100-cb9e-11ea-8074-065237a28207.png)
Plus the update isn't real time here - https://rahuldkjain.github.io, update happens when the page reloads.
I was thinking of real time update, instead of reloading.

**Comment by ankurchaudhary627** [comment]
I've checked in the code and raised a PR. Thanks. @rahuldkjain

**Comment by abhijit-hota** [comment]
Have been looking at this issue for a while. 
My two cents:

The counts don't necessarily have to be "real-time". They are just counts and I think a single API fetch after the first render is enough. Making them real-time, in my opinion, is just overkill. 

A simple solution would be to make the API call and just display the count like @ankurchaudhary627 did [here](https://github.com/rahuldkjain/github-profile-readme-generator/issues/7#issuecomment-661116292) and just style them to fix their layouts.

**Comment by prakashchokalingam** [comment]
We can use https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event to refresh the counts. I can help you with a PR. @rahuldkjain

**Comment by rahuldkjain** [comment]
> I've checked in the code and raised a PR. @rahuldkjain Thanks.

I think there is no need to update the count every 15 seconds. The average usage time per user on the page is 59 seconds.

**Comment by rahuldkjain** [comment]
> We can use https://developer.mozilla.org/en-US/docs/Web/API/Document/visibilitychange_event to refresh the counts. I can help you with a PR. @rahuldkjain
> 
> When user clicks the fork button, he will be taken to the github in a new tab, after forking when he returns back to the page we can update the counts using the visibility Api.
> 
> And we can have a long interval updates as well which shouldn't create a problem.

Thanks @prakashchokalingam  for your efforts.
P.S: Please put a comment to assign the issue before start working.

**Comment by prakashchokalingam** [comment]
Thanks @rahuldkjain 

It's just a reference PR @rahuldkjain, It is not created with an intent to merge. will be closing the PR.

**Comment by rahuldkjain** [comment]
fixed

**Comment by yashu1wwww** [comment]
Github Tools:
https://yashawanthtechprojects.on.drv.tw/GitHub/uploaddatefinder.html
