### ISSUE TITLE
Hashnode logo under  "connect with me" - update to new one

### ISSUE THREAD

**Issue by AnirudhaPatil-1** [rahuldkjain/github-profile-readme-generator#724]
The svg for hashnode in following path: 
 [https://raw.githubusercontent.com/rahuldkjain/github-profile-readme-generator/master/src/images/icons/Social/hashnode.svg](url)
is old one.

Could you please update the log to new one .

Thank you for the github readme generator. 

Keep up the good work

**Comment by Vsoni27** [comment]
Please assign this issue to me

**Comment by Vsoni27** [comment]
I have made a PR where I have updated the hashnode.svg hope it will solve the required task.
