### ISSUE TITLE
add Gimp badge in software section

### ISSUE THREAD

**Issue by carafelix** [rahuldkjain/github-profile-readme-generator#731]
Gimp is a nice open-source alternative to Photoshop or similar image manipulation tools. 
Adding it to the badge collection would be a nice touch nice, for ex, I use it all the time.

**Comment by AshkanArabim** [comment]
I'm interested in tackling this issue. Could this be assigned to me?

**Comment by AshkanArabim** [comment]
Okay just so I know what's going on, should I do anything or not? The issue is marked as completed.

**Comment by g-savitha** [comment]
Someone has fixed it.
