### ISSUE TITLE
Add Skills for Devops Engineer

### ISSUE THREAD

**Issue by AcidBurn18** [rahuldkjain/github-profile-readme-generator#747]
Major Skill Missing

Terraform
Ansible
Gitlab
Prometheus
Jira
Chef
Kibana
etc

**Comment by sagnik3788** [comment]
i want to  work on this issue please assign me @AcidBurn18 @vivek32ta

**Comment by Vsoni27** [comment]
Can you assign this issue to me

**Comment by shivamshahi07** [comment]
I would like to work on this issue and I intend to add more necessary skills for DevOps engineers than already mentioned in the issue. (like ELK, SELENIUM, GRADLE, PUPPET, etc.)
Please assign this issue to me.
Thanks

**Comment by archikirar30** [comment]
@AcidBurn18 I have pushed my changes, can you please review and check.

**Comment by archikirar30** [comment]
@AcidBurn18 I have pushed my changes, can you please review and check it.

**Comment by archikirar30** [comment]
Should I be specific about the DevOps or I can add more missing skills in every section ?

**Comment by archikirar30** [comment]
@AcidBurn18 @Vsoni27 Can you review and check again ? I have added more skills under DevOps section .
