### ISSUE TITLE
Some Icons are not Visible

### ISSUE THREAD

**Issue by Prathamesh2802** [rahuldkjain/github-profile-readme-generator#748]
![bug](https://github.com/rahuldkjain/github-profile-readme-generator/assets/96346665/59c4c6f9-bdf3-46f0-a590-7855c46535bb)
Icons Such as Github, hackerrank, leetcode etc are not visible.

**Comment by mohammed-7** [comment]
same here , i tried them but they are not displayed on profile

**Comment by shubham221716** [comment]
ctrl +shift +R

**Comment by shubham221716** [comment]
some time it is not visible due to slow internet connection, so use the fast internet.
I also feel the same problem . 
you can do ctrl + shift +R

**Comment by deveshkoli** [comment]
The icons are visible. But the icons vector images/ logos are not designed as per the dark theme on Github. You can change your profile appearance to a light mode. 

To change to a light theme - 

goto -
1. https://github.com/settings/profile
2. Click appearances on the left side bar on website
![image](https://github.com/rahuldkjain/github-profile-readme-generator/assets/122155089/afd4fc14-3488-423a-b292-59375a53e736)
3. Then choose the a light theme according to your like.

This will make all the icons visible as well as there wouldn't be any blank spaces for the icons where dark theme is a problem.

**Comment by mohammed-7** [comment]
i guess there might be problem with vector graphics.
