### ISSUE TITLE
[BUG]Languages' icons are above the "Most Used Languages" title

### ISSUE THREAD

**Issue by DestroyerXyz** [rahuldkjain/github-profile-readme-generator#75]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
![image](https://user-images.githubusercontent.com/70191184/91149794-28802580-e6d9-11ea-8209-2ebcf72bace6.png)

**Comment by rahuldkjain** [comment]
@DestroyerXyz since you don't have any repository yet, the most languages thing will be empty. I suggest you to not use it right now.
