### ISSUE TITLE
Add Leetcode stats section

### ISSUE THREAD

**Issue by aman4uas** [rahuldkjain/github-profile-readme-generator#765]
There is no section to add leetcode user's profile Stats. 

There should be a Leetcode stats showing similar to the leetcode user's profile.

![image](https://github.com/rahuldkjain/github-profile-readme-generator/assets/96907045/639be494-7dc0-43e2-a8c7-d7fd95859844)

**Comment by aman4uas** [comment]
@rahuldkjain  Can you please assign this to me

**Comment by GaganChaudhary6378** [comment]
Hi , can you please assign it to me?

**Comment by RydKrm** [comment]
Hi, I would like to solve this issue.

**Comment by harshul-2002** [comment]
sir please assign this to me i can solve this
