### ISSUE TITLE
Qt and others

### ISSUE THREAD

**Issue by guillaume-larche** [rahuldkjain/github-profile-readme-generator#78]
**Is your feature request related to a problem? Please describe.**
That will be great if there had the Qt and other GUI frameworks available in the **frontend** category. 

**Describe the solution you'd like**
Add Qt, wxWidgets and GTK icons within the **frontend** category

![2020-08-27 12_42_28-Window](https://user-images.githubusercontent.com/22976322/91443436-a2e4ad00-e873-11ea-991e-337925cffd51.png)

**Comment by rahuldkjain** [comment]
@guillaume-larche would you like to work on this?

**Comment by MauricioHernanCabrera** [comment]
I can do that @rahuldkjain

**Comment by guillaume-larche** [comment]
@MauricioHernanCabrera it's ok for me !

**Comment by rahuldkjain** [comment]
fixed by #92
