### ISSUE TITLE
Tech stack PNG are not loading

### ISSUE THREAD

**Issue by ibrahim-hn** [rahuldkjain/github-profile-readme-generator#781]
**Describe the bug**
When added tech stack, respective PNG images are not loaded.

**Comment by Manasranjanpati** [comment]
Yes I have also see this issue.

**Comment by Omsoni06** [comment]
can you please describe this issue in details ,

**Comment by ibrahim-hn** [comment]
Yes,

1.Go to readme creator
2.Add the tech stack (Choose some technologies like React, Angular, JS etc)
3.and generate .md file
4.Now copy generated code to your readme.md file

ISSUE - you will see that some of the tech stack selected PNG image is not visible (loaded)

**Comment by ibrahim-hn** [comment]
Yes,

1.Go to readme creator
2.Add the tech stack (Choose some technologies like React, Angular, JS etc)
3.and generate .md file
4.Now copy generated code to your readme.md file

ISSUE - you will see that some of the tech stack selected PNG image is not visible (loaded)

**Comment by ibrahim-hn** [comment]
Yes,

1.Go to readme creator
2.Add the tech stack (Choose some technologies like React, Angular, JS etc)
3.and generate .md file
4.Now copy generated code to your readme.md file

ISSUE - you will see that some of the tech stack selected PNG image is not visible (loaded)
