### ISSUE TITLE
Blog posts dynamically from personal website

### ISSUE THREAD

**Issue by g-savitha** [rahuldkjain/github-profile-readme-generator#80]
Add blog posts to display dynamically from personal website.

**Comment by rahuldkjain** [comment]
@g-savitha this will be a great addition. It is possible using if the personal blog support RSS Feed.

Would you like to work on it?

**Comment by g-savitha** [comment]
yes. please assign this to me

**Comment by rahuldkjain** [comment]
@g-savitha what's the status?

**Comment by g-savitha** [comment]
Hi, haven't started working on this yet. 
Can you give me a head start to get started with this. I have no idea, how to start :|

**Comment by rahuldkjain** [comment]
@g-savitha refer this https://github.com/gautamkrishnar/blog-post-workflow

**Comment by g-savitha** [comment]
Gotcha. Ok my plan for this enhancement is we just need to add another input field where a user can enter his RSS Feed URL and will display another checkbox similar to Dev.to and medium at the bottom.
