### ISSUE TITLE
Add Astro.dev framework

### ISSUE THREAD

**Issue by nick747** [rahuldkjain/github-profile-readme-generator#808]
Add the Astro.dev framework to the skills. An icon like this one from Skill-Icons:

![Astro](https://github.com/rahuldkjain/github-profile-readme-generator/assets/84738664/01ffbfb2-19e3-4301-962b-ef4f4de40ad3)

**Comment by g-savitha** [comment]
Would you like to work on it?

**Comment by nick747** [comment]
@g-savitha see if this looks good, I've never worked on this project.

https://github.com/rahuldkjain/github-profile-readme-generator/pull/809
