### ISSUE TITLE
View Count increments if you keep reloading the webpage !!

### ISSUE THREAD

**Issue by LuGO0** [rahuldkjain/github-profile-readme-generator#87]
**Describe the bug**
View count keeps on increasing if we keep on reloading the webpage and even while editing also this behavior can be seen.
**To Reproduce**
1. Go to readme or edit the readme
2. reload it 
3. see the incremented count

**Expected behavior**
no change in count should be expected

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Vadorequest** [comment]
https://github.com/antonkomarev/github-profile-views-counter/issues/15

**Comment by rahuldkjain** [comment]
Please refer https://rahuldkjain.github.io/gh-profile-readme-generator/about

**Comment by LuGO0** [comment]
perfect get the problem @rahuldkjain !! maybe we should pin this issue so that It dosent gets raised anymore .
closing it 👍
