### ISSUE TITLE
integrate GitHub Profile Trophy in addons

### ISSUE THREAD

**Issue by ryo-ma** [rahuldkjain/github-profile-readme-generator#89]
I have developed GitHub Profile Trophy.

https://github.com/ryo-ma/github-profile-trophy

Can you integrate into the functionality in the same like as Github readme stats?

<img width="1317" alt="スクリーンショット 2020-08-30 22 03 37" src="https://user-images.githubusercontent.com/6661165/91737154-a8caed00-ebe9-11ea-83f8-18f2e3449094.png">

**Comment by rahuldkjain** [comment]
This looks cool ⚡️. Will definitely integrate.

**Comment by ryo-ma** [comment]
Thanks!

**Comment by g-savitha** [comment]
this looks great @ryo-ma  :)

**Comment by ryo-ma** [comment]
Thank you! @g-savitha

**Comment by ryo-ma** [comment]
@rahuldkjain 
How about this issue?

**Comment by rahuldkjain** [comment]
Will definitely integrate in a few days!

**Comment by sarbikbetal** [comment]
can I take this?

**Comment by jaideepghosh** [comment]
Hey @rahuldkjain
I want to contribute to solve this issue. Please assign it to me.

**Comment by g-savitha** [comment]
@sarbikbetal are you working on this?

**Comment by sarbikbetal** [comment]
Yeah but it's fine if there's a PR, unassign me and merge it if you like.
