### ISSUE TITLE
Add dribbble, behance, medium, & youtube input box in social

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#9]
![github-profile-readme-generator social](https://user-images.githubusercontent.com/26406279/87868599-4610ef80-c9b5-11ea-848e-4b3a08191f56.png)
See the above image for reference

Use these links for icons
dribbble: https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/dribbble.svg
behance: https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/behance.svg
medium: https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/medium.svg
youtube: https://cdn.jsdelivr.net/npm/simple-icons@3.1.0/icons/youtube.svg

**Comment by abhijit-hota** [comment]
Is someone working on this issue?

**Comment by rahuldkjain** [comment]
Nope @abhijit-hota . I am assigning it to you

**Comment by abhijit-hota** [comment]
> Nope @abhijit-hota . I am assigning it to you

Working on it. Thanks!

**Comment by abhijit-hota** [comment]
#13 Added it! Please review and merge!

**Comment by rahuldkjain** [comment]
fix: https://github.com/rahuldkjain/github-profile-readme-generator/pull/13
