### ISSUE TITLE
github-readme-stats option hides HTML language automatically

### ISSUE THREAD

**Issue by JoseDeFreitas** [rahuldkjain/github-profile-readme-generator#90]
I noticed that when you use the "Top Languages" card from the [github-readme-stats](https://github.com/anuraghazra/github-readme-stats) repository the HTML language gets automatically hidden, which I think it shouldn't.
I think the default "Top Languages" card should be generated with the default settings (`https://github-readme-stats.vercel.app/api/top-langs/?username=anuraghazra`).
I've read about having a system to customize the card, which will let you hide any language if you want; but still, in my opinion, the card should be the default (before the customization).

Have a great day 🖖.

**Comment by rahuldkjain** [comment]
@JoseDeFreitas  would you like to work on it?

**Comment by JoseDeFreitas** [comment]
@rahuldkjain no, it was just some thought I have and something I would like to see implemented. Thank you anyway 😀✌
