### ISSUE TITLE
GitHub Highlight Badges Integration

### ISSUE THREAD

**Issue by louis-e** [rahuldkjain/github-profile-readme-generator#91]
Maybe consider integrating the GitHub user badges like the _Arctic Code Vault Contribution_ badge or the _Pro_ badge.

**Comment by rahuldkjain** [comment]
Sure, would you like to contribute?

**Comment by louis-e** [comment]
Do you know if this would be possible to integrate? After a bit of thinking I still have no idea ^^

**Comment by g-savitha** [comment]
Hey @louis-e you can do it. Check this out.  https://github.com/arturssmirnovs/github-profile-readme-generator. This person has coded in vue.js

**Comment by louis-e** [comment]
Sure, I could contribute and make a function to let the user select his badges.
I thought about making it automatically by crawling the user badges. I thought too complicated😅

**Comment by louis-e** [comment]
Does anyone know if the icons (https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/personalizing-your-profile#displaying-badges-on-your-profile) are free to use?

**Comment by rahuldkjain** [comment]
@louis-e @g-savitha is there any need to show these badges again on the GitHub profile because it's already displayed on the profile left panel. Just curious to know your thoughts.

**Comment by rahuldkjain** [comment]
> Does anyone know if the icons (https://docs.github.com/en/github/setting-up-and-managing-your-github-profile/personalizing-your-profile#displaying-badges-on-your-profile) are free to use?

You can use these for free https://primer.style/octicons/

**Comment by g-savitha** [comment]
Yeah even I feel they are redundant. Since @louis-e was curious about it, I shared the resource :D . What are your thoughts @louis-e ?

**Comment by louis-e** [comment]
That was just an idea, but your'e right, it's superfluous 👍🏻
