### ISSUE TITLE
Names don't show up when hovering over the "skills" checkboxes (on desktop)

### ISSUE THREAD

**Issue by kathawala** [rahuldkjain/github-profile-readme-generator#93]
**Describe the bug**
Hovering over the skills in the part where you fill out the form to generate the README, sometimes the skill names do not appear even though there's enough space for them to appear

**To Reproduce**
1. Open your desktop browser, to any width lower than 1199px
2. Hover mouse over the checkboxes in the skills section.
3. No name for the corresponding logos shows up.

**Expected behavior**
As long as the width allows for it, the names for the corresponding logos should show up when they are hovered over in the skills section.

**Screenshots**
[screencast](https://i.imgur.com/venPVNU.mp4)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 80.0 

**Additional context**
Please assign the issue to me, I've already written the fix for it (it's just a change to media queries in CSS).

**Comment by rahuldkjain** [comment]
Would you like to work on it?

**Comment by kathawala** [comment]
Yes please assign it to me
