### ISSUE TITLE
apply prettier to the whole project

### ISSUE THREAD

**Issue by rahuldkjain** [rahuldkjain/github-profile-readme-generator#96]
Currently, the code formatting is not consistent across the project.

Preferred Formatting:
- Intend using tabs
- default tab size: 4

Use prettier to achieve the same

**Comment by amruta-kashikar** [comment]
I would like to work on this. Please assign this to me

**Comment by ShubhamSood1406** [comment]
Hey assign it to me I would like to work on it.

**Comment by g-savitha** [comment]
did someone made a PR to this?

**Comment by g-savitha** [comment]
assign this to me if no one has made a PR yet.

**Comment by g-savitha** [comment]
This is fixed here :  https://github.com/rahuldkjain/github-profile-readme-generator/pull/108
