### ISSUE TITLE
Update DSA social links with proper URLs

### ISSUE THREAD

**Issue by g-savitha** [rahuldkjain/github-profile-readme-generator#97]
Hi, DSA social links are not redirected to exact pages.
Often user is ending up with 404 pages.

**Comment by g-savitha** [comment]
Assign this to me.

**Comment by g-savitha** [comment]
Fixed this. 

Ref : https://github.com/rahuldkjain/github-profile-readme-generator/pull/102

**Comment by rahuldkjain** [comment]
fixed by #102
