### ISSUE TITLE
CodeForces and CodeChef links throws 'Page not found' error

### ISSUE THREAD

**Issue by AnonySharma** [rahuldkjain/github-profile-readme-generator#99]
**Describe the bug**
When we create a link for CodeForces and CodeChef using this generator, it lands to some unusual page.

**To Reproduce**
1. Add your handle in CodeForces and CodeChef section.
2. Click on the resulted image button.
3. See error.

**Comment by AnonySharma** [comment]
Assign this to me.

**Comment by g-savitha** [comment]
Hey @AnonySharma this issue has been fixed here. https://github.com/rahuldkjain/github-profile-readme-generator/pull/102 . Let me know if you face any issues :)
